### ISSUE TITLE
输出色彩最后要关闭（RESET）

### ISSUE THREAD

**Issue by waylonwang** [ainewsto/Comfyui_Comfly#2]
AiHelper.py中print("\033[32m ** Comfly Loaded :\033[33m fly, just fly")最后加上\033[0m，否则后面comfyui的输出都被污染成黄色了。
建议改成：
print("\033[32m ** Comfly Loaded :\033[33m fly, just fly\033[0m")

**Comment by ainewsto** [comment]
非常感谢，已经修改！
